name: Run Partitioned Tests
description: |
    Run partitioned tests with cargo nextest

inputs:
  partition:
    description: "Partition to run"
    required: true
  total-partitions:
    description: "Total number of partitions"
    required: true
  archive-file:
    description: "Archive file to use for tests"
    required: true
    default: "~/test_archive.tar.zst"
  failure-output:
    description: "Failure output"
    required: false
    default: "final"
  success-output:
    description: "Success output"
    required: false
    default: "never"
  status-level:
    description: "Output status level"
    required: false
    default: "fail"
  retries:
    description: "Number of test retries"
    required: false
    default: "2"

runs:
  using: "composite"
  steps:
    # Run unit tests in a partition
    - name: Run Partitioned Tests
      shell: bash
      run: |
        export LLVM_PROFILE_FILE="test-results-%p-%m.profraw" && \
        cargo nextest run \
          --retries ${{ inputs.retries }} \
          --fail-fast \
          --failure-output ${{ inputs.failure-output }} \
          --success-output ${{ inputs.success-output }} \
          --status-level ${{ inputs.status-level }} \
          --archive-file ${{ inputs.archive-file }} \
          --partition count:${{ inputs.partition }}/${{ inputs.total-partitions }}
