
[project]
name = "core-contracts"

[repl]
costs_version = 1

[contracts.bns]
path = "../../stackslib/src/chainstate/stacks/boot/bns.clar"
depends_on = []
epoch = 2.4

[contracts.signers]
path = "../../stackslib/src/chainstate/stacks/boot/signers.clar"
depends_on = []
clarity = 2
epoch = 2.4

[contracts.signers-voting]
path = "../../stackslib/src/chainstate/stacks/boot/signers-voting.clar"
depends_on = []
clarity = 2
epoch = 2.4

[contracts.pox-4]
path = "../../stackslib/src/chainstate/stacks/boot/pox-4.clar"
clarity_version = 2
epoch = 2.4
depends_on = ["pox-mainnet"]

[contracts.pox-mainnet]
path = "../../stackslib/src/chainstate/stacks/boot/pox-mainnet.clar"
clarity_version = 2
epoch = 2.4
depends_on = []

[contracts.bns_test]
path = "./tests/bns_test.clar"
clarity_version = 2
epoch = 2.4

[contracts.pox_4_test]
path = "./tests/pox_4_test.clar"
clarity_version = 2
epoch = 2.4
