name: Create Releases
description: |
    Wrapper workflow to create GitHub Releases

inputs:
    node_tag:
        description: "Node Release Tag"
        required: true
    signer_tag:
        description: "Signer Release Tag"
        required: true
    digest_manifest:
        description: "Path to docker digest manifest directory (optional)"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        # Checkout the code
        - name: Checkout the latest code
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          with:
            ref: ${{ github.event.pull_request.head.sha || github.ref }}

        # Creates the node release
        - name: Create Node Release
          if: inputs.node_tag != ''
          uses: ./.github/actions/release/create-github-release
          with:
              tag: ${{ inputs.node_tag }}
              release_type: stacks-core
              digest_manifest: ${{ inputs.digest_manifest }}

        # Creates the signer release
        - name: Create Signer Release
          if: inputs.signer_tag != ''
          uses: ./.github/actions/release/create-github-release
          with:
              tag: ${{ inputs.signer_tag }}
              release_type: stacks-signer
              digest_manifest: ${{ inputs.digest_manifest }}
