FROM rust:bookworm

WORKDIR /src/

COPY . .

WORKDIR /src/testnet/stacks-node

RUN rustup component add llvm-tools-preview && \
    cargo install grcov

ENV RUSTFLAGS="-Cinstrument-coverage" \
    LLVM_PROFILE_FILE="stacks-blockchain-%p-%m.profraw"

RUN apt-get -y install libllvm16 libclang1-16

RUN cargo test --no-run && \
    cargo build

RUN cd / && wget https://bitcoin.org/bin/bitcoin-core-25.0/bitcoin-25.0-x86_64-linux-gnu.tar.gz
RUN cd / && tar -xvzf bitcoin-25.0-x86_64-linux-gnu.tar.gz

RUN ln -s /bitcoin-25.0/bin/bitcoind /bin/

ENV BITCOIND_TEST 1
