FROM rust:bullseye AS test

WORKDIR /build

ENV CARGO_MANIFEST_DIR="$(pwd)"

RUN apt update

RUN apt install -y parallel

RUN rustup component add llvm-tools-preview && \
    cargo install grcov

ENV RUSTFLAGS="-Cinstrument-coverage" \
    LLVM_PROFILE_FILE="stacks-blockchain-%p-%m.profraw"

COPY . .

RUN cargo build --workspace && \
    cd clarity/fuzz && \
    cargo build --workspace

RUN echo $(cargo fuzz list) | tr ' ' "\n" | parallel -I% --lb --max-args 1 -k "echo % && cargo fuzz run % -- -max_total_time=3600 -rss_limit_mb=4096"
