FROM blockstack/stacks-blockchain:2.05.0.2.0-stretch as stacks-node

FROM rust:stretch AS test

WORKDIR /build

RUN rustup override set nightly-2022-01-14 && \
    rustup component add llvm-tools-preview && \
    cargo install grcov

ENV RUSTFLAGS="-Zinstrument-coverage" \
    LLVM_PROFILE_FILE="stacks-blockchain-%p-%m.profraw" \
    STACKS_NODE_TEST="1"

COPY --from=stacks-node /bin/stacks-node /bin/

COPY . .

RUN cargo build --workspace && \
    cargo test --workspace --bin=hyperchain-node --no-run

