FROM rust:bullseye AS test

WORKDIR /build

ENV CARGO_MANIFEST_DIR="$(pwd)"

RUN rustup component add llvm-tools-preview && \
    cargo install grcov

ENV RUSTFLAGS="-Cinstrument-coverage" \
    LLVM_PROFILE_FILE="stacks-blockchain-%p-%m.profraw"

COPY . .

RUN cargo build --workspace && \
    cd clarity/fuzz && \
    cargo build --workspace && \
    cargo fuzz run fuzz_admits_type -- -max_total_time 1800 && \
    cargo fuzz run fuzz_least_supertype -- -max_total_time 1800
