FROM rust:bullseye AS test

WORKDIR /build

ENV CARGO_MANIFEST_DIR="$(pwd)"

RUN rustup component add llvm-tools-preview && \
    cargo install grcov

ENV RUSTFLAGS="-Cinstrument-coverage" \
    LLVM_PROFILE_FILE="stacks-blockchain-%p-%m.profraw"

COPY . .

RUN cargo build --workspace && \
    cd clarity/fuzz && \
    cargo build --workspace && \
    for target in $(cargo fuzz list) \
    do \
        cargo fuzz run $target -- -max_total_time=1800 -rss_limit_mb=4096 \
    done
