# For more configuration details: https://docs.codecov.com/docs/codecovyml-reference
# Check if this file is valid: curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 270 # this should be updated occasionally to stay within ~20 of total files uploaded
    wait_for_ci: true
    notify_error: true
coverage:
  range: 60..79
  round: down
  precision: 2
  status:
    project:
      default: false
      clarity:
        target: auto
        threshold: 0%
        removed_code_behavior: adjust_base
        if_not_found: success
        if_ci_failed: success
        only_pulls: true
        paths:
          - clarity-types
          - clarity
      contrib:
        target: auto
        threshold: 0%
        removed_code_behavior: adjust_base
        if_not_found: success
        if_ci_failed: success
        only_pulls: true
        paths:
          - contrib
      core:
        target: auto
        threshold: 0%
        removed_code_behavior: adjust_base
        if_not_found: success
        if_ci_failed: success
        only_pulls: true
        paths:
          - libsigner
          - libstackerdb
          - pox-locking
          - stacks-common
          - stacks-node
          - stacks-signer
          - stackslib
          - stx-genesis
    patch:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: success
        only_pulls: true
        paths:
          - clarity-types
          - clarity
          - contrib
          - libsigner
          - libstackerdb
          - pox-locking
          - stacks-common
          - stacks-node
          - stacks-signer
          - stackslib
          - stx-genesis
    changes: false
comment:
  layout: "condensed_header, diff, files, footer"
  behavior: default
  hide_project_coverage: false
  require_changes: false
  require_base: true
  require_head: true
github_checks:
  annotations: false