version: 2
jobs:
  deploy:
    working_directory: /build
    docker:
      - image: rust:1.34.0-stretch
    steps:
      - checkout
      - run:
          command: |
            bash build-scripts/start-builds.sh
      - store_artifacts:
          path: /build/dist/
          destination: dist/
  test_demo:
    working_directory: /test
    docker:
      - image: rust:1.34.0-stretch
    steps:
      - checkout
      - run:
          command: |
            cargo build --release && cargo install --path . 
      - run:
          command: |
            blockstack-core local initialize db &&
            blockstack-core local check sample-programs/tokens.clar db &&
            blockstack-core local launch tokens sample-programs/tokens.clar db &&
            blockstack-core local check sample-programs/names.clar db &&
            blockstack-core local launch names sample-programs/names.clar db &&
            blockstack-core local execute db tokens mint! SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR 100000
      - run:
          command: |
            echo "(get-balance 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR)" | blockstack-core local eval tokens db
  build:
    machine: true
    working_directory: ~/blockstack
    steps:
      - checkout
      - run:
          name: Pull Cargo Tarpaulin Image
          command: |
            docker pull xd009642/tarpaulin
      - run:
          name: Run tests in Cargo Tarpaulin Image
          command: |
            docker run --security-opt seccomp=unconfined -e RUST_BACKTRACE=1 -e BLOCKSTACK_DEBUG=1 \
            -e RUSTFLAGS=-Clink-dead-code -v "$PWD:/volume" xd009642/tarpaulin cargo tarpaulin -t 300 -o Xml \
            -- --test-threads 1
      - run:
          name: Test that Cargo Tarpaulin Suceeded
          command: test -e cobertura.xml
      - run:
          name: Upload to codecov.io
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test_demo
      - deploy
