FROM rust:bullseye as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'

WORKDIR /src

COPY . .

RUN mkdir /out

RUN cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release

RUN cp target/release/stacks-node /out

FROM debian:bullseye-slim

RUN apt update && apt install -y netcat
COPY --from=build /out/ /bin/

CMD ["stacks-node", "mainnet"]
