FROM rust:stretch as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'

WORKDIR /src

COPY . .

RUN mkdir /out

RUN cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release

RUN cp target/release/hyperchain-node /out

FROM debian:stretch-slim

RUN apt update && apt install -y netcat openssl
COPY --from=build /out/ /bin/

CMD ["hyperchain-node", "mainnet"]
