FROM rust:bullseye as build

ARG STACKS_NODE_VERSION="No Version Info"
ARG GIT_BRANCH='No Branch Info'
ARG GIT_COMMIT='No Commit Info'

WORKDIR /src

COPY . .

RUN mkdir /out

RUN cd testnet/stacks-node && cargo build --release --bin mempool-analyzer

RUN cp target/release/mempool-analyzer /out

FROM debian:bullseye-slim

RUN apt update && apt install -y netcat cron
COPY --from=build /out/ /bin/

CMD ["mempool-analyzer", "/hirosystems/data", "600000"]
