# This is a wrapper since this action is used in several workflows. goal is to have a single file to update to a new commit
name: Install Tools
description: |
  Wrapper for the `taiki-e/install-action` action to install required tools.
inputs:
  tools:
    description: Comma-separated list of tools to install
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    # Install the defined input.tool
    - name: Install Tool(s)
      uses: taiki-e/install-action@65851e10cd6c377f11a60e600abc07cb08643468 # v2.79.3
      with:
        tool: ${{ inputs.tools }}
