FROM rust:latest

WORKDIR /src/stacks-core

RUN apt-get update
RUN apt-get install valgrind heaptrack -y
RUN apt-get install less

RUN rustup install stable

COPY . .

RUN cargo test --no-run 

CMD ["bash"]
