#!/bin/bash

# This script provides a simple interface for folks to use the docker install

bitcoindimage=quay.io/blockstack/bitcoind-regtest
bitcoindtag=latest

build-btc () {
  echo "Building integration bitcoind image..."
  docker build -t $bitcoindimage:latest .
}

build-dev () {
  echo "Building image from git branch $(git rev-parse HEAD)"
  docker build -f docker/Dockerfile.dev -t $coreimage:$gitrev
  docker tag $coreimage:$gitrev $coreimage:dev
}


commands () {
  cat <<-EOF
blockstack docker launcher commands:
  setup -> run the setup for blockstack and generate a wallet
  start -> start the blockstack api server
  browser -> run the two browser containers as well
  logs -> access the logs from the blockstack api server
  enter -> exec into the running docker container
  stop -> stop the blockstack api server
EOF
}

case $1 in
  build)
    build 
    ;;
  build-dev)
    build-dev 
    ;;
  *)
    commands
    ;;
esac
