MEMCACHED_USERNAME = None
MEMCACHED_PASSWORD = None

NAMECOIND_SERVER = 'localhost'
NAMECOIND_PORT = 8332
NAMECOIND_USER = 'default'
NAMECOIND_PASSWD = 'default'
MEMCACHED_SERVERS = ['127.0.0.1:11211']

try:
    API_USERNAME = os.environ['API_USERNAME']
    API_PASSWORD = os.environ['API_PASSWORD']
except:
    API_USERNAME = API_PASSWORD = ''
