FROM rust:stretch as build

WORKDIR /src

COPY . .

RUN rustup target add x86_64-unknown-linux-musl

RUN apt-get update && apt-get install -y musl-tools

RUN CC=musl-gcc \
    CC_x86_64_unknown_linux_musl=musl-gcc \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc \
    cargo build --release --workspace=./ --target x86_64-unknown-linux-musl

FROM scratch AS export-stage
COPY --from=build /src/target/x86_64-unknown-linux-musl/release /