name: Run Tests
description: |
    Run tests sequentially with cargo nextest using a regex batch pattern

inputs:
  test-names:
    description: "Comma-separated list of literal test names to run"
    required: true
  archive-file:
    description: "Archive file to use for tests"
    required: true
    default: "~/test_archive.tar.zst"
  failure-output:
    description: "Failure output"
    required: false
    default: "final"
  success-output:
    description: "Success output"
    required: false
    default: "never"
  status-level:
    description: "Output status level"
    required: false
    default: "fail"
  retries:
    description: "Number of test retries"
    required: false
    default: "2"

runs:
  using: "composite"
  steps:
    # Run a provided batch of tests sequentially
    - name: Run Tests
      shell: bash
      run: |
        export LLVM_PROFILE_FILE="test-results-%p-%m.profraw"
        # Force nextest to run tests 1 at a time to prevent race conditions
        export NEXTEST_PROFILE_DEFAULT_TEST_THREADS=1
        
        # Convert CSV string to Nextest exact-match Filterset format
        # e.g., "a, b" becomes "test(=a)|test(=b)"
        FILTERSET=$(echo "${{ inputs.test-names }}" | sed -E 's/[[:space:]]*,[[:space:]]*/)|test(=/g')
        FILTERSET="test(=${FILTERSET})"

        cargo nextest run \
          --archive-file ${{ inputs.archive-file }} \
          --retries ${{ inputs.retries }} \
          --run-ignored all \
          --fail-fast \
          --failure-output ${{ inputs.failure-output }} \
          --success-output ${{ inputs.success-output }} \
          --status-level ${{ inputs.status-level }} \
          -E "$FILTERSET"