#!/bin/bash

ops () {

  local python=/usr/bin/python
  local initCore=blockstack-core-init
  local storageBucket=https://blockstack.blob.core.windows.net/index
  local image=quay.io/blockstack/blockstack-core
  local tag=master

  init-api () {
    local apiData=data/blockstack-api
    echo "Initializing Blockstack Core API server with dummy wallet..."
    mkdir -p $apiData
    docker run -it --rm \
      -v $(pwd)/$apiData:/root/.blockstack \
      $image:$tag \
      blockstack setup -y --password dummywalletpassword
    sudo cp deployment/client.ini $apiData/client.ini
  }

  init-indexer () {
    local idxData=data/search-api
    echo "Initializing Blockstack Indexer with dummy data..."
    mkdir -p $idxData
    cp search/fixtures/blockchain_data.json $idxData/blockchain_data.json
    cp search/fixtures/profile_data.slice.json $idxData/profile_data.slice.json
  }

  commands () {
    cat <<-EOF
ops commands:
  init-api     -> Set up the dummy wallet for the core api
  init-indexer -> Set up the bootstrapping data for the indexer
EOF
  }

  case $1 in
    init-api)
      init-api
      ;;
    init-indexer)
      init-indexer
      ;;
    *)
      commands
      ;;
  esac

}

ops $1 $2
