name: "Checks: Nix"
run-name: "Checks: Nix [${{ github.ref_name }}]"

on:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - master
      - develop
      - next
    paths-ignore:
      - "**.md"
      - "**.yml"
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

# Set default permissions
permissions:
  contents: read

# Configure concurrency
concurrency:
  group: nix-${{ github.head_ref || github.ref || github.run_id }}
  # Always cancel duplicate jobs
  cancel-in-progress: true

jobs:
  build-pkg:
    name: Check Nix package
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      # Install Nix
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      # Run the check
      - run: nix flake check ./contrib/nix
