# Perform Clippy checks - currently set to defaults
#   https://github.com/rust-lang/rust-clippy#usage
#   https://rust-lang.github.io/rust-clippy/master/index.html
#
name: "Checks: Clippy"
run-name: "Checks: Clippy [${{ github.ref_name }}]"

# Only run when:
#   - PRs are (re)opened against develop branch
#   - commit is pushed to PR
#   - PR is added to merge queue
on:
  workflow_dispatch:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize

# Set default permissions
permissions:
  contents: read

# Configure concurrency
concurrency:
  group: clippy-${{ github.head_ref || github.ref || github.run_id }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  clippy-stacks:
    name: Clippy Check (stacks)
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      # Setup the default rust toolchain with clippy
      - name: Setup Rust Toolchain
        uses: ./.github/actions/setup-rust-toolchain
        with:
          components: clippy

      # Run clippy with clippy-stacks alias in .cargo/config.toml
      - name: Clippy
        run: cargo clippy-stacks

  clippy-stacks-lib:
    name: Clippy Check (stackslib)
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      # Setup the default rust toolchain with clippy
      - name: Setup Rust Toolchain
        uses: ./.github/actions/setup-rust-toolchain
        with:
          components: clippy

      # Run clippy with clippy-stackslib alias in .cargo/config.toml
      - name: Clippy Stackslib
        run: cargo clippy-stackslib
