name: Seed Caches

################################################################################################################################
# GitHub caches are scoped to branches, with a fallback mechanism:
#   1. A branch can only see caches created on that branch
#   2. Failing that, a branch can opt-in to looking at the base branch cache
#   3. Failing that, a branch can always access the default branch caches (`main` or `master`)
# So we build caches on `main` nightly, since our branches typically target `main` as base.
# That allows PR branches to re-use these caches, via `restore-keys` fallback in the actions/cache GitHub action.
# The cache restore is intentionally broad: it will restore what `main` currently has.
# If the branch has updated dependencies, cargo will notice the mismatched versions (or new deps) and build them on-the-fly.
#
# NOTE: This job only runs on `main` branch of `stacks-network/stacks-core` OR if GitHub Action var is set: SEED_CACHES = true
################################################################################################################################

on:
  schedule:
    # Run at 00:00 UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering / seeding
  push:
    branches:
      - main

permissions:
  contents: read

# Configure concurrency
#   - cache will exist longer than workflow execution so other runners have access.
#   - this must be atomic and never run in parallel
concurrency:
  group: seed-caches
  cancel-in-progress: false

jobs:
  ##############################################################################
  ### Create Reusable Caches for Tests
  ###
  ### Caches can only be created from `main`. This workflow runs only from 
  ### `main` and therefore will successfully create canonical re-usable caches.
  ##############################################################################
  setup-test-caches:
    name: "Create: Test Caches"
    # Execute if running in our core repo on `main` OR if SEED_CACHES GitHub Actions variable is 'true'
    if: |
      (github.repository == 'stacks-network/stacks-core' && github.ref_name == 'main') ||
      vars.SEED_CACHES == 'true'
    uses: ./.github/workflows/setup-test-caches.yml