## Github workflow to run bitcoin tests

name: Tests::Bitcoin

on:
  workflow_call:

## env vars are transferred to composite action steps
env:
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  TEST_TIMEOUT: 30

concurrency:
  group: bitcoin-tests-${{ github.head_ref || github.ref || github.run_id}}
  ## Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  generate-tests:
    name: Generate JSON of tests to run
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      ## Setup test environment
      - name: Setup Test Environment
        id: setup_tests
        uses: stacks-network/actions/stacks-core/testenv@main
        with:
          btc-version: "25.0"
      - name: Generate tests JSON
        id: generate_tests_json
        run: |
          cargo nextest list --run-ignored only --bin stacks-node -Tjson | \
          jq '.["rust-suites"]["stacks-node::bin/stacks-node"]["testcases"] | map_values(select(.["ignored"] == true)) | keys' > ./tests.json
      - id: set-matrix
        run: |
          json_obj=`cat ./tests.json`
          echo "::set-output name=matrix::$JSON"

  # Bitcoin integration tests with code coverage
  integration-tests:
    needs: generate-tests
    name: Integration Tests
    runs-on: ubuntu-latest
    strategy:
      ## Continue with the test matrix even if we've had a failure
      fail-fast: false
      ## Run a maximum of 32 concurrent tests from the test matrix
      max-parallel: 32
      matrix:
        test-name: ${{fromJson(needs.generate-tests.outputs.matrix)}}
        exclude:
          - test: tests::bitcoin_regtest::bitcoind_integration_test_segwit
          - test: tests::epoch_205::bigger_microblock_streams_in_2_05
          - test: tests::epoch_205::test_cost_limit_switch_version205
          - test: tests::epoch_205::test_dynamic_db_method_costs
          - test: tests::epoch_205::test_exact_block_costs
          - test: tests::epoch_205::transition_empty_blocks
          - test: tests::epoch_21::test_pox_missing_five_anchor_blocks
          - test: tests::epoch_21::test_pox_reorg_flap_duel
          - test: tests::epoch_21::test_pox_reorg_flap_reward_cycles
          - test: tests::epoch_21::test_pox_reorg_one_flap
          - test: tests::epoch_21::test_pox_reorgs_three_flaps
          - test: tests::epoch_21::test_sortition_divergence_pre_21
          - test: tests::epoch_21::test_v1_unlock_height_with_current_stackers
          - test: tests::epoch_21::test_v1_unlock_height_with_delay_and_current_stackers
          - test: tests::epoch_21::trait_invocation_cross_epoch
          - test: tests::epoch_21::transition_adds_burn_block_height
          - test: tests::epoch_21::transition_adds_get_pox_addr_recipients
          - test: tests::epoch_21::transition_adds_mining_from_segwit
          - test: tests::epoch_21::transition_adds_pay_to_alt_recipient_contract
          - test: tests::epoch_21::transition_adds_pay_to_alt_recipient_principal
          - test: tests::epoch_21::transition_empty_blocks
          - test: tests::epoch_21::transition_fixes_bitcoin_rigidity
          - test: tests::epoch_21::transition_removes_pox_sunset
          - test: tests::epoch_22::disable_pox
          - test: tests::epoch_22::pox_2_unlock_all
          - test: tests::epoch_22::test_pox_reorg_one_flap
          - test: tests::epoch_23::trait_invocation_behavior
          - test: tests::epoch_24::fix_to_pox_contract
          - test: tests::epoch_24::verify_auto_unlock_behavior
          - test: tests::epoch_25::microblocks_disabled
          - test: tests::integrations::integration_test_get_info
          - test: tests::nakamoto_integrations::block_proposal_api_endpoint
          - test: tests::nakamoto_integrations::burn_ops_integration_test
          - test: tests::nakamoto_integrations::check_block_heights
          - test: tests::nakamoto_integrations::check_block_info
          - test: tests::nakamoto_integrations::check_block_info_rewards
          - test: tests::nakamoto_integrations::check_block_times
          - test: tests::nakamoto_integrations::clarity_burn_state
          - test: tests::nakamoto_integrations::clarity_cost_spend_down
          - test: tests::nakamoto_integrations::consensus_hash_event_dispatcher
          - test: tests::nakamoto_integrations::continue_tenure_extend
          - test: tests::nakamoto_integrations::correct_burn_outs
          - test: tests::nakamoto_integrations::flash_blocks_on_epoch_3
          - test: tests::nakamoto_integrations::follower_bootup_across_multiple_cycles
          - test: tests::nakamoto_integrations::follower_bootup_custom_chain_id
          - test: tests::nakamoto_integrations::follower_bootup_simple
          - test: tests::nakamoto_integrations::forked_tenure_is_ignored
          - test: tests::nakamoto_integrations::mine_invalid_principal_from_consensus_buff
          - test: tests::nakamoto_integrations::mine_multiple_per_tenure_integration
          - test: tests::nakamoto_integrations::miner_writes_proposed_block_to_stackerdb
          - test: tests::nakamoto_integrations::mock_mining
          - test: tests::nakamoto_integrations::multiple_miners
          - test: tests::nakamoto_integrations::nakamoto_attempt_time
          - test: tests::nakamoto_integrations::nakamoto_lockup_events
          - test: tests::nakamoto_integrations::signer_chainstate
          - test: tests::nakamoto_integrations::simple_neon_integration
          - test: tests::nakamoto_integrations::sip029_coinbase_change
          - test: tests::nakamoto_integrations::skip_mining_long_tx
          - test: tests::nakamoto_integrations::test_shadow_recovery
          - test: tests::nakamoto_integrations::test_tenure_extend_from_flashblocks
          - test: tests::nakamoto_integrations::utxo_check_on_startup_panic
          - test: tests::nakamoto_integrations::utxo_check_on_startup_recover
          - test: tests::nakamoto_integrations::v3_blockbyheight_api_endpoint
          - test: tests::nakamoto_integrations::v3_signer_api_endpoint
          - test: tests::nakamoto_integrations::vote_for_aggregate_key_burn_op
          - test: tests::neon_integrations::antientropy_integration_test
          - test: tests::neon_integrations::atlas_integration_test
          - test: tests::neon_integrations::atlas_stress_integration_test
          - test: tests::neon_integrations::bad_microblock_pubkey
          - test: tests::neon_integrations::bitcoin_reorg_flap
          - test: tests::neon_integrations::bitcoin_reorg_flap_with_follower
          - test: tests::neon_integrations::bitcoind_forking_test
          - test: tests::neon_integrations::bitcoind_integration_test
          - test: tests::neon_integrations::bitcoind_resubmission_test
          - test: tests::neon_integrations::block_large_tx_integration_test
          - test: tests::neon_integrations::block_limit_hit_integration_test
          - test: tests::neon_integrations::block_replay_integration_test
          - test: tests::neon_integrations::confirm_unparsed_ongoing_ops
          - test: tests::neon_integrations::cost_voting_integration
          - test: tests::neon_integrations::deep_contract
          - test: tests::neon_integrations::filter_long_runtime_tx_integration_test
          - test: tests::neon_integrations::filter_low_fee_tx_integration_test
          - test: tests::neon_integrations::filter_txs_by_origin
          - test: tests::neon_integrations::filter_txs_by_type
          - test: tests::neon_integrations::fuzzed_median_fee_rate_estimation_test_window10
          - test: tests::neon_integrations::fuzzed_median_fee_rate_estimation_test_window5
          - test: tests::neon_integrations::liquid_ustx_integration
          - test: tests::neon_integrations::listunspent_max_utxos
          - test: tests::neon_integrations::lockup_integration
          - test: tests::neon_integrations::microblock_fork_poison_integration_test
          - test: tests::neon_integrations::microblock_integration_test
          - test: tests::neon_integrations::microblock_large_tx_integration_test_FLAKY
          - test: tests::neon_integrations::microblock_limit_hit_integration_test
          - test: tests::neon_integrations::microblock_miner_multiple_attempts
          - test: tests::neon_integrations::min_txs
          - test: tests::neon_integrations::miner_submit_twice
          - test: tests::neon_integrations::mining_events_integration_test
          - test: tests::neon_integrations::mock_miner_replay
          - test: tests::neon_integrations::most_recent_utxo_integration_test
          - test: tests::neon_integrations::pox_integration_test
          - test: tests::neon_integrations::push_boot_receipts
          - test: tests::neon_integrations::run_with_custom_wallet
          - test: tests::neon_integrations::runtime_overflow_unconfirmed_microblocks_integration_test
          - test: tests::neon_integrations::should_fix_2771
          - test: tests::neon_integrations::size_check_integration_test
          - test: tests::neon_integrations::size_overflow_unconfirmed_invalid_stream_microblocks_integration_test
          - test: tests::neon_integrations::size_overflow_unconfirmed_microblocks_integration_test
          - test: tests::neon_integrations::size_overflow_unconfirmed_stream_microblocks_integration_test
          - test: tests::neon_integrations::stack_stx_burn_op_test
          - test: tests::neon_integrations::start_stop_bitcoind
          - test: tests::neon_integrations::stx_delegate_btc_integration_test
          - test: tests::neon_integrations::stx_transfer_btc_integration_test
          - test: tests::neon_integrations::test_chainwork_first_intervals
          - test: tests::neon_integrations::test_chainwork_partial_interval
          - test: tests::neon_integrations::test_competing_miners_build_anchor_blocks_and_microblocks_on_same_chain
          - test: tests::neon_integrations::test_competing_miners_build_anchor_blocks_on_same_chain_without_rbf
          - test: tests::neon_integrations::test_flash_block_skip_tenure
          - test: tests::neon_integrations::test_one_miner_build_anchor_blocks_on_same_chain_without_rbf
          - test: tests::neon_integrations::test_problematic_blocks_are_not_mined
          - test: tests::neon_integrations::test_problematic_blocks_are_not_relayed_or_stored
          - test: tests::neon_integrations::test_problematic_microblocks_are_not_mined
          - test: tests::neon_integrations::test_problematic_microblocks_are_not_relayed_or_stored
          - test: tests::neon_integrations::test_problematic_txs_are_not_stored
          - test: tests::neon_integrations::use_latest_tip_integration_test
          - test: tests::neon_integrations::vote_for_aggregate_key_burn_op_test
          - test: tests::should_succeed_handling_malformed_and_valid_txs
          - test: tests::signer::v0::allow_reorg_within_first_proposal_burn_block_timing_secs
          - test: tests::signer::v0::bitcoind_forking_test
          - test: tests::signer::v0::block_commit_delay
          - test: tests::signer::v0::block_proposal_max_age_rejections
          - test: tests::signer::v0::block_proposal_rejection
          - test: tests::signer::v0::block_proposal_timeout
          - test: tests::signer::v0::block_validation_pending_table
          - test: tests::signer::v0::block_validation_response_timeout
          - test: tests::signer::v0::continue_after_fast_block_no_sortition
          - test: tests::signer::v0::continue_after_tenure_extend
          - test: tests::signer::v0::duplicate_signers
          - test: tests::signer::v0::empty_sortition
          - test: tests::signer::v0::empty_sortition_before_approval
          - test: tests::signer::v0::empty_sortition_before_proposal
          - test: tests::signer::v0::end_of_tenure
          - test: tests::signer::v0::fast_sortition
          - test: tests::signer::v0::forked_tenure_invalid
          - test: tests::signer::v0::forked_tenure_okay
          - test: tests::signer::v0::global_acceptance_depends_on_block_announcement
          - test: tests::signer::v0::idle_tenure_extend_active_mining
          - test: tests::signer::v0::incoming_signers_ignore_block_proposals
          - test: tests::signer::v0::injected_signatures_are_ignored_across_boundaries
          - test: tests::signer::v0::locally_accepted_blocks_overriden_by_global_rejection
          - test: tests::signer::v0::locally_rejected_blocks_overriden_by_global_acceptance
          - test: tests::signer::v0::min_gap_between_blocks
          - test: tests::signer::v0::mine_2_nakamoto_reward_cycles
          - test: tests::signer::v0::miner_forking
          - test: tests::signer::v0::miner_gather_signatures
          - test: tests::signer::v0::miner_recovers_when_broadcast_block_delay_across_tenures_occurs
          - test: tests::signer::v0::mock_sign_epoch_25
          - test: tests::signer::v0::multiple_miners
          - test: tests::signer::v0::multiple_miners_empty_sortition
          - test: tests::signer::v0::multiple_miners_mock_sign_epoch_25
          - test: tests::signer::v0::multiple_miners_with_custom_chain_id
          - test: tests::signer::v0::multiple_miners_with_nakamoto_blocks
          - test: tests::signer::v0::new_tenure_while_validating_previous_scenario
          - test: tests::signer::v0::no_reorg_due_to_successive_block_validation_ok
          - test: tests::signer::v0::outgoing_signers_ignore_block_proposals
          - test: tests::signer::v0::partial_tenure_fork
          - test: tests::signer::v0::rejected_blocks_count_towards_miner_validity
          - test: tests::signer::v0::reloads_signer_set_in
          - test: tests::signer::v0::reorg_locally_accepted_blocks_across_tenures_fails
          - test: tests::signer::v0::reorg_locally_accepted_blocks_across_tenures_succeeds
          - test: tests::signer::v0::retry_on_rejection
          - test: tests::signer::v0::signer_set_rollover
          - test: tests::signer::v0::signers_broadcast_signed_blocks
          - test: tests::signer::v0::signing_in_0th_tenure_of_reward_cycle
          - test: tests::signer::v0::single_miner_empty_sortition
          - test: tests::signer::v0::stx_transfers_dont_effect_idle_timeout
          - test: tests::signer::v0::tenure_extend_after_2_bad_commits
          - test: tests::signer::v0::tenure_extend_after_bad_commit
          - test: tests::signer::v0::tenure_extend_after_failed_miner
          - test: tests::signer::v0::tenure_extend_after_idle_miner
          - test: tests::signer::v0::tenure_extend_after_idle_signers
          - test: tests::signer::v0::tenure_extend_succeeds_after_rejected_attempt
          - test: tests::stackerdb::test_stackerdb_event_observer
          - test: tests::stackerdb::test_stackerdb_load_store

    steps:
      ## Setup test environment
      - name: Setup Test Environment
        id: setup_tests
        uses: stacks-network/actions/stacks-core/testenv@main
        with:
          btc-version: "25.0"

      ## Increase open file descriptors limit
      - name: Increase Open File Descriptors
        run: |
          sudo prlimit --nofile=4096:4096

      ## Run test matrix using restored cache of archive file
      ##   - Test will timeout after env.TEST_TIMEOUT minutes
      - name: Run Tests
        id: run_tests
        timeout-minutes: ${{ fromJSON(env.TEST_TIMEOUT) }}
        uses: stacks-network/actions/stacks-core/run-tests@main
        with:
          test-name: ${{ matrix.test-name }}
          threads: 1

      ## Create and upload code coverage file
      - name: Code Coverage
        id: codecov
        uses: stacks-network/actions/codecov@main
        with:
          test-name: ${{ matrix.test-name }}

  check-tests:
    name: Check Tests
    runs-on: ubuntu-latest
    if: always()
    needs:
      - integration-tests
    steps:
      - name: Check Tests Status
        id: check_tests_status
        uses: stacks-network/actions/check-jobs-status@main
        with:
          jobs: ${{ toJson(needs) }}
          summary_print: "true"
