## The main Github Actions workflow
name: CI

on:
  merge_group:
    types:
      - checks_requested
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"
      - "**.yml"
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.head_ref || github.ref || github.run_id }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

run-name: ${{ github.ref_name }}

jobs:
  get-approval-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch protection rules
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            repos/${{ github.repository }}/branches/develop/protection/required_pull_request_reviews \
            --jq '{
              required_approving_review_count: .required_approving_review_count,
              dismiss_stale_reviews: .dismiss_stale_reviews,
              require_code_owner_reviews: .require_code_owner_reviews
            }'

