name: Core build tests

# Only run when:
#   - PRs are (re)opened against develop branch
on:
  workflow_call:
    
jobs:
  check-consts:
    name: Check the constants from stacks-inspect
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Define Rust Toolchain
        id: define_rust_toolchain
        run: echo "RUST_TOOLCHAIN=$(cat ./rust-toolchain)" >> $GITHUB_ENV
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      ## run cargo check steps
      - name: Cargo Check
        id: cargo_check
        run: |
          cargo check

      - name: Cargo Check (monitoring_prom)
        id: cargo_check_prom
        run: |
          cargo check --features monitoring_prom

      - name: Cargo Check (clarity)
        id: cargo_check_clarity
        run: |
          cargo check -p clarity --no-default-features

      - name: Cargo Check (stacks-common)
        id: cargo_check_stacks-common
        run: |
          cargo check -p stacks-common --no-default-features

      - name: Dump constants JSON
        id: consts-dump
        run: |
          cargo run --bin stacks-inspect -- dump-consts | tee out.json

      ## output any diff to the github job summary
      - name: Compare expected constants JSON
        id: expects-json
        run: |
          diff out.json ./sample/expected_consts.json >> $GITHUB_STEP_SUMMARY
