name: "Create: Test Caches"
run-name: "Create: Test Caches [${{ github.ref_name }}]"

################################################################################################################################
# GitHub caches are scoped to branches, with a fallback mechanism:
#   1. A branch by default can only see caches created on that branch
#   2. Failing that, a branch can opt-in to accessing the base branch cache
#   3. If the base branch cache is missing, the opt-in check will fall through to the default branch cache (`main`)
#
# So we build caches on `main` after each push, since our branches typically target `main` as base.
#
# This allows any and all PR branches that ultimately derive from `main` to re-use these caches for faster 
# CI workflows, via an intentionally broad `restore-keys` fallback in the actions/cache GitHub action.
#
# The broad cache restore will find the most recently created (newest) caches in `main`.
#
# If the branch has updated cargo crates, or the cache is slightly stale, that's OK.
# The cargo build process will notice the mismatched versions (or new deps) automatically 
# and build them on-the-fly. This allows slightly stale caches to still be very useful.
#
# NOTE: 
#   This job ONLY runs if a GitHub Action variable is set: ENABLE_CI_WORKFLOWS = true
################################################################################################################################

on:
  workflow_dispatch: # Allows manual triggering / seeding
  push:
    branches:
      - main

permissions:
  contents: read

# Configure concurrency
#   - cache will exist longer than workflow execution so other runners have access.
#   - when multiple pushes to `main` happen in a short time, cancel 
#     the current run and start the new one with the most recent code.
concurrency:
  group: create-caches
  cancel-in-progress: true

# Env vars
env:
  # The version of the bitcoin binary to use for tests
  BTC_VERSION: "31.1"
  # The SHA of the binary to verify before executing the tests. Find these in the official SHA256SUMS file for each release. Example: https://bitcoincore.org/bin/bitcoin-core-31.1/SHA256SUMS
  BTC_VERSION_SHA: "b80d9c3e04da78fb6f0569685673418cf686fadba9042d926d13fb87ff503f9e"

jobs:
  # Check if CI is enabled
  check-ci:
    name: "Check: CI Enabled"
    uses: ./.github/workflows/__check-ci.yml

  ############################################################################
  ### Global Variables Setup
  ###
  ### Bridges global env variables to the jobs context so they are safely
  ### accessible by downstream reusable workflows.
  ### Also defines default runs-on anchor.
  ############################################################################
  setup-env:
    name: "Setup: Global Variables"
    needs:
      - check-ci
    if: needs.check-ci.outputs.enabled == 'true'
    runs-on: &shared_config ubuntu-latest
    outputs:
      btc-version: ${{ steps.set-env.outputs.btc_version }}
      btc-version-sha: ${{ steps.set-env.outputs.btc_version_sha }}
    steps:
      - name: Export Env Variables
        id: set-env
        run: |
          echo "btc_version=$BTC_VERSION" >> $GITHUB_OUTPUT
          echo "btc_version_sha=$BTC_VERSION_SHA" >> $GITHUB_OUTPUT

  #######################################################################################################################
  ### Create Reusable Caches for Tests
  ###
  ### Caches are created from `main` branch when a GitHub Action variable is set: ENABLE_CI_WORKFLOWS = true
  ### When run on `main`, this workflow creates canonical re-usable caches for future CI runs.
  ### When manually dispatched from another branch, any created caches will be scoped to that branch.
  #######################################################################################################################
  cache-bitcoin-binary:
    name: "Create: Bitcoin Binary Cache"
    needs:
      - setup-env
    runs-on: *shared_config
    steps:
      # Checkout the code
      #   - only .github is required for this job
      - name: Checkout the latest code
        uses: $/.github/wrappers/checkout
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github
    
      # Check cache for bitcoin binary
      # We don't need multiple caches of the same Bitcoin binary, so skip create if one already exists
      - name: Check Bitcoin Cache
        id: bitcoin
        uses: ./.github/actions/cache/bitcoin
        with:
          action: check
          btc-version: ${{ steps.setup-env.outputs.btc-version }}
          btc-version-sha: ${{ steps.setup-env.outputs.btc-version-sha }}

      # Only create when a binary doesn't already exist
      - name: Create Bitcoin Cache
        if: >-
          !steps.bitcoin.outputs.cache-matched-key
        uses: ./.github/actions/cache/bitcoin
        with:
          action: create
          btc-version: ${{ steps.setup-env.outputs.btc-version }}
          btc-version-sha: ${{ steps.setup-env.outputs.btc-version-sha }}

  cache-cargo:
    name: "Create: Cargo Cache"
    needs:
      - check-ci
    if: needs.check-ci.outputs.enabled == 'true'
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      #   - only .github is required for this job
      - name: Checkout the latest code
        uses: $/.github/wrappers/checkout
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github
    
      - name: Create Cargo Cache
        uses: ./.github/actions/cache/cargo
        with:
          action: create
