# Workflow to lock closed PRs/issues/discussions
# timeframe to lock defaults to:
#    issues: 30 days
#    prs: 30 days
#    discussions: 365 days

name: "Lock Threads"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# Set default permissions
permissions:
  issues: write
  pull-requests: write
  discussions: write

# Configure concurrency
concurrency:
  group: lock-threads

jobs:
  # Lock closed issues/prs/discussions
  lock:
    name: Lock Threads
    runs-on: ubuntu-latest
    steps:
      - name: Lock Threads
        uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 7
          pr-inactive-days: 14
          discussion-inactive-days: 7
