## Workflow to lock closed PRs/issues/discussions
## timeframe to lock defaults to:
##    issues: 30 days
##    prs: 30 days
##    discussions: 365 days

name: "Lock Threads"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  ## Lock closed issues/prs/discussions
  lock:
    name: Lock Threads
    runs-on: ubuntu-latest
    steps:
      - name: Lock Threads
        id: lock_threads
        uses: stacks-network/actions/lock-threads@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: 7
          pr-inactive-days: 7
          discussion-inactive-days: 7
    
