# Github workflow to run p2p tests

name: Tests::P2P

on:
  workflow_dispatch:
    inputs:
      build-cache:
        type: boolean
        default: true
        description: Build the test cache before running tests
  workflow_call:

# Set default permissions
permissions:
  contents: read

# Set default env vars
#  - transferred to composite action steps
env:
  BITCOIND_TEST: 0
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 15
  TEST_TIMEOUT: 30

# Configure concurrency
concurrency:
  group: stackslib-tests-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # P2P integration tests with code coverage
  integration-tests:
    name: Integration Tests
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    strategy:
      # Continue with the test matrix even if we've had a failure
      fail-fast: false
      matrix:
        test-name:
          - net::tests::convergence::test_walk_ring_allow_15
          - net::tests::convergence::test_walk_ring_15_plain
          - net::tests::convergence::test_walk_ring_15_pingback
          - net::tests::convergence::test_walk_ring_15_org_biased
          - net::tests::convergence::test_walk_line_allowed_15
          - net::tests::convergence::test_walk_line_15_plain
          - net::tests::convergence::test_walk_line_15_org_biased
          - net::tests::convergence::test_walk_line_15_pingback
          - net::tests::convergence::test_walk_star_allowed_15
          - net::tests::convergence::test_walk_star_15_plain
          - net::tests::convergence::test_walk_star_15_pingback
          - net::tests::convergence::test_walk_star_15_org_biased
          - net::tests::convergence::test_walk_inbound_line_15
          - net::api::tests::postblock_proposal::test_try_make_response
          - net::server::test::test_http_10_threads_getinfo
          - net::server::test::test_http_10_threads_getblock
          - net::server::test::test_http_too_many_clients
          - net::server::test::test_http_slow_client
    steps:
      # Checkout the code
      #   - only .github is required for this job
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github

      # Download cache(s) and configure the runner to run test(s)
      - name: Setup Test Environment
        uses: ./.github/actions/testenv

      # Run test matrix
      #   - test will timeout after ${TEST_TIMEOUT} minutes
      - name: Run Tests
        timeout-minutes: ${{ env.TEST_TIMEOUT }}
        uses: ./.github/actions/run-tests
        with:
          test-names: ${{ matrix.test-name }}

      # Create and upload code coverage file
      - name: Code Coverage
        if: github.event.repository.visibility == 'public'
        uses: ./.github/actions/codecov
        with:
          test-name: ${{ matrix.test-name }}

  # Check that all jobs in this workflow have succeeded.
  #   - will not run if the job is cancelled
  check-tests:
    name: Check Tests
    needs:
      - integration-tests
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      #   - only .github is required for this job
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github

      # Check if all jobs succeeded
      - name: Check Jobs Status
        shell: bash
        env:
          JOBS: ${{ toJson(needs) }}
          SUMMARY_PRINT: "true"
        run: bash ./.github/scripts/check_jobs_status.sh
