# Github workflow to run full genesis and unit tests

name: "Tests: Stacks Core"

on:
  workflow_call:
    inputs:
      archive-file:
        description: "The test archive file"
        required: true
        type: string

# Set default permissions
permissions:
  contents: read

# Set default env vars
#   - transferred to composite action steps
env:
  NUM_UNIT_TEST_PARTITIONS: 16
  BITCOIND_TEST: 1
  RUST_BACKTRACE: full
  TEST_TIMEOUT: 30

# Configure concurrency
concurrency:
  group: stacks-core-tests-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Set up the unit test matrix
  setup-unit-test-matrix:
    name: Setup Unit Test Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-array: ${{ steps.setup-matrix.outputs.result }}
    steps:
      - id: setup-matrix
        run: |
          # Generates a JSON array like [1, 2, 3, ..., 16] using jq
          ARRAY=$(seq 1 ${{ env.NUM_UNIT_TEST_PARTITIONS }} | jq -s -c .)
          echo "result=$ARRAY" >> $GITHUB_OUTPUT

  # Unit tests with code coverage
  unit-tests:
    name: Unit Tests
    needs:
      - setup-unit-test-matrix
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    # Continue the workflow in case a step fails (ex a single test fails)
    # continue-on-error: true
    strategy:
      # Continue the workflow in case a step fails (ex a single test fails)
      fail-fast: false
      matrix:
        # Partition unit tests into env.NUM_UNIT_TEST_PARTITIONS concurrent jobs
        partition: ${{ fromJSON(needs.setup-unit-test-matrix.outputs.matrix-array) }}
    steps:
    # Checkout the code
    #   - only .github is required for this job
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github

      # Setup, run tests, generate and upload code coverage artifact
      - name: Setup + Run Tests + Codecov
        timeout-minutes: ${{ fromJSON(env.TEST_TIMEOUT) }}
        uses: ./.github/actions/run-tests
        with:
          partition: ${{ matrix.partition }}
          total-partitions: ${{ strategy.job-total }}
          codecov-test-name: ${{ github.job }}-${{ matrix.partition }}
          archive-file: ${{ inputs.archive-file }}

  # Generate and upload openapi html artifact
  open-api-validation:
    name: OpenAPI Validation
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Generate OpenAPI documentation
        uses: ./.github/actions/openapi
        with:
          input: "./docs/rpc/openapi.yaml"
          output: "./openapi-docs.html"
          config: "./docs/rpc/redocly.yaml"
          validate: "true"
          redocly-version: "2.19"

  # Generate and upload node configuration documentation
  node-config-docsgen:
    name: Node Configuration Documentation
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Generate Node Configuration Documentation
        uses: ./.github/actions/config-docsgen

  # Core contract tests
  core-contracts-clarinet-test:
    name: Core Contracts Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./contrib/core-contract-tests/"
    steps:
      # Checkout the code
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Execute core contract unit tests with clarinet-sdk
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 25.x
          cache: "npm"
          cache-dependency-path: "./contrib/core-contract-tests/package-lock.json"
      - run: npm ci
      - run: npm test

  # Check that all jobs in this workflow have succeeded.
  #   - will not run if the job is cancelled
  check-tests:
    name: Check Tests
    needs:
      - unit-tests
      - open-api-validation
      - node-config-docsgen
      - core-contracts-clarinet-test
    if: always() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      #   - only .github is required for this job
      - name: Checkout the latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          sparse-checkout: |
            .github

      # Check if all jobs succeeded
      - name: Check Jobs Status
        shell: bash
        env:
          JOBS: ${{ toJson(needs) }}
          SUMMARY_PRINT: "true"
        run: bash ./.github/scripts/check_jobs_status.sh
